services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        UID: 1001
        GID: 1001
    container_name: atividade_app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public

  db:
    image: mariadb:11
    container_name: atividade_db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: tarefas
      MARIADB_USER: tarefas
      MARIADB_PASSWORD: tarefas
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3309:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: atividade_pma
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    depends_on:
      - db
  
  node:
    image: node:20
    container_name: atividade_node
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    profiles: ["tools"]
  
volumes:
  dbdata:
